// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clearusers.sql

package database

import (
	"context"
)

const clearTable = `-- name: ClearTable :exec
TRUNCATE TABLE users
`

func (q *Queries) ClearTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearTable)
	return err
}
